config/routes.rb
Rails.application.routes.draw do
  resources 'topics', only: [:show, :index]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'html_css_items', to: 'portfolios#html_css'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount  ActionCable.server => '/cable'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true, 
                                reject_if: lambda { |attributes| attributes['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.html_css
    where(subtitle: 'HTML & CSS')
  end

  def self.by_position
    order('position ASC')
  end

  scope :html_css_items_only, -> { where(subtitle: 'HTML & CSS') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :find_portfolio_item, only: [:show, :edit, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :html_css], user: { except: [:destroy, :new, :create, :update, :edit, :sort] }, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
  end

  def html_css
    @html_css_items = Portfolio.html_css_items_only
  end

  def show
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Your portfolio item was created" }
      else
        format.html { render 'new' }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'You updated the portfolio item' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed' }
    end
  end

  private

  def portfolio_params
    params.require('portfolio').permit(:title,
                                       :subtitle,
                                       :body,
                                       :thumb_image,
                                       :main_image,
                                       technologies_attributes: [:name, :id, :_destroy]
                                       )
  end

  def find_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    if img
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
<% if @portfolio_item.errors.any? %>
  <% @portfolio_item.errors.full_messages.each do |error| %>
    <%= render 'shared/error_messages', error: error %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label class="btn btn-primary">
        Upload a main image file <%= f.file_field :main_image, style: 'display: none;' %>
      </label>
    </div>

    <div class="form-group">
      <label class="btn btn-primary">
        Upload a thumb image file <%= f.file_field :thumb_image, style: 'display: none;' %>
      </label>
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control', rows: 13 %>
    </div>
  </div>
</div>

<hr>

<h3> Technologies used </h3>
<div>
  <%= f.fields_for :technologies do |technology_form| %>
    <%= render 'technology_fields', f: technology_form %>
  <% end %>

  <%= link_to_add_association 'Add Technology', f, :technologies %>
</div>

<div class="mt-3">
  <%= render partial: 'shared/admin_action_icons', locals: { object: @portfolio_item, edit_path: edit_portfolio_path(@portfolio_item) } %>
</div>

<div class="actions mt-3">
  <%= f.submit 'Save portfolio item', class: 'btn btn-primary btn-block' %>
</div>

<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-id=<%= portfolio_item.id %> >
    <p> <%= image_tag(portfolio_img(portfolio_item.thumb_image.url, 'thumb'), width: '100%') %>
    </p>
    <div class="card-body">
      <p class="card-text">
        <span>
          <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
        </span>
          <%= portfolio_item.subtitle %>
      </p>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container mt-5">
  <h1> Edit this portfolio item </h1>
  <div>
    <%= render 'form', portfolio_item: @portfolio_item %>
  </div>
</div>

app/views/portfolios/html_css.html.erb
<h1> HTML and CSS Portfolio </h1>

<%= link_to 'Create new item', new_portfolio_path %>

<% @html_css_items.each do |item| %>
  <div>
    <h3> <%= link_to item.title, portfolio_show_path(item) %> </h3>
    <p> <%= item.subtitle %> </p>
    <p> <%= item.body %> </p>
    <p> <%= image_tag(item.main_image) unless item.main_image.nil? %> </p>
    <p> <%= image_tag(item.thumb_image) unless item.thumb_image.nil? %> </p>
  </div>
  <div>
    <%= link_to 'Show', portfolio_show_path(item) %>
    <%= link_to 'Edit', edit_portfolio_path(item) if logged_in?(:site_admin) %>
    <%= link_to 'Delete Portfolio item', portfolio_path(item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= link_to('Create new item', new_portfolio_path, class: 'btn btn-primary mb-4') if logged_in?(:site_admin) %>
    <div class="row <%= 'sortable' if logged_in?(:site_admin) %>" >
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container mt-5">
  <h1> Create a new portfolio item </h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container mt-3 portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag(portfolio_img(@portfolio_item.main_image.url, 'main'), width: '100%') %>
    </div>
    <div class="col-md-5">
      <h1> <%= @portfolio_item.title %> </h1>
      <hr>
      <em> <%= @portfolio_item.subtitle %> </em>
      <p> <%= @portfolio_item.body %> </p>
      <hr>
      <h3> Technologies used: </h3>
      <% @portfolio_item.technologies.each do |technology| %>
        <p> <%= technology.name %> </p>
      <% end %>

      <%= render partial: 'shared/admin_action_icons', locals: { object: @portfolio_item, edit_path: edit_portfolio_path(@portfolio_item) } %>
    </div>

  </div>
</div>