config/routes.rb
Rails.application.routes.draw do
  resources 'topics', only: [:show, :index]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'html_css_items', to: 'portfolios#html_css'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount  ActionCable.server => '/cable'
end

app/views/shared/_admin_action_icons.html.erb
<span class="admin-action-icons">
  <%= link_to fa_icon('edit'), edit_path if logged_in?(:site_admin) %>
  <%= link_to fa_icon('trash'), object, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } if logged_in?(:site_admin) %>
</span>

app/views/shared/_alerts.html.erb
<% flash.each do |type, message| %>
  <% formatted_type = notification_type_format(type) %>
  <div id='notification' data-type="<%= formatted_type %>" data-message="<%= message %>"></div>
  <%= javascript_pack_tag 'alerts' %>
<% end %>

app/views/shared/_application_navbar.html.erb
<header class="masthead ">
  <div class="inner">
    <h3 class="masthead-brand">Theresa Mannschatz</h3>
    <nav class="nav nav-masthead justify-content-center application-nav">
      <%= navbar_helper('nav-link', 'span') %>
      <%= login_helper('nav-link') %>
    </nav>
  </div>
</header>

app/views/shared/_blog_header.html.erb
<div class="col-4 text-left">
  <%= link_to "<em>Quer</em>einsteiger".html_safe, blogs_path, class: 'blog-header-logo text-dark' %>
  <div class="mt-3">
    <%= link_to('Write a new post', new_blog_path, class: 'btn btn-primary') if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav_scroller.html.erb
<div class="nav-scroller py-1 mb-5">
  <nav class="nav d-flex justify-content-between">
    <% most_popular_topics_helper.each do |topic_id|  %>
      <%= link_to topic_name_helper(topic_id), topic_path(topic_id), class: "p-2 text-muted" %>
    <% end %>
  </nav>
</div>

app/views/shared/_blog_navbar.html.erb
<div class="col-8 d-flex justify-content-end align-items-center">
  <a class="text-muted" href="#" aria-label="Search">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
  </a>
  <%= navbar_helper('nav-link', 'span') %>
  <%= login_helper('btn-outline-secondary nav-link btn') %>
</div>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <%= source_helper('alert alert-info blog-sidebar-source') %> 

  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Welcome to my blog 'my way into coding'. I am a <em>Quereinsteiger</em> and started with coding in 2018 during parental leave of our first child. I would like to document and share my thoughts and learnings on my way to become a professional full-stack developer.</p>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Topics</h4>
    <% @sidebar_topics.each do |topic| %>
      <p> <%= link_to topic.title, topic_path(topic.id) %> </p>
    <% end %>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-media-links">
      <li> <%= link_to "#{fab_icon 'github'}".html_safe, 'https://github.com/Resetete' %> </li>
      <li> <%= link_to "#{fab_icon 'linkedin'}".html_safe, 'https://www.linkedin.com/in/theresa-mannschatz-975b598a/' %> </li>
      <li> <%= link_to "#{fas_icon 'envelope-square'}".html_safe, 'mailto:contact@theresamannschatz.design' %> </li>
      <li> <%= link_to "#{fab_icon 'behance-square'}".html_safe, 'https://www.behance.net/rese_m9404' %> </li>
    </ol>
  </div>
</aside>

app/views/shared/_error_messages.html.erb
<div class='badge badge-danger mb-3'>
  <%= error %>
</div>

app/views/shared/_footer.html.erb
<footer class=<%=styles%>>
  <p>
    <%= link_to 'Back to top', '#' %>
  </p>
  <div>
    <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View all portfolios', portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<div class="container">
  <%= source_helper('alert alert-info portfolio-source-helper') %>
</div>

<section class="jumbotron text-center">
  <div class="container">
    <h1>Work examples</h1>
    <p class="lead text-muted">That are some of my projects I was working on. Most of them are tutorial projects, but there are also some for Clients.</p>
    <p>
      <%= link_to 'Find out more about me', about_me_path, class: "btn btn-primary my-2" %>
      <%= link_to 'My blog', blogs_path, class: "btn btn-secondary my-2" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_navbar.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Here you can explore some of my web development projects. If you like have a look at my very own first portfolio website. It is a simple HTML&CSS playful static page with some js. </p>
          <p> <%= link_to 'theresamannschatz.design', 'theresamannschatz.design', class: 'badge' %> </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= navbar_helper('text-white', 'li')%>
            <li><%= login_helper('btn-outline-secondary text-white btn') %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>Theresa Mannschatz</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>