config/routes.rb
Rails.application.routes.draw do
  resources 'topics', only: [:show, :index]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'html_css_items', to: 'portfolios#html_css'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount  ActionCable.server => '/cable'
end

app/views/layouts/_navbar.html.erb
<div>
  <div> <%= link_to 'Home', root_path %> </div>
  <div> <%= link_to 'About', about_me_path %>  </div>
  <div> <%= link_to 'Contact', contact_path %>  </div>
  <div> <%= link_to 'Blog', blogs_path %>  </div>
  <div> <%= link_to 'Portfolio', portfolios_path %>  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @page_title %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    <meta name='keywords' content="<%= @seo_keywords %>"/>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Slab:wght@200&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <% if Rails.env.production? %>
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-K8CS3TDTTP"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
      </script>
    <% end %>
  </head>

  <body>
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <div id="background"></div>
      <%= video_tag('videobgd2.mp4',
                     id: 'background',
                     autoplay: true,
                     loop: true,
                     muted: true,
                     poster: 'bgd-home.png') %>

      <%= render 'shared/application_navbar' %>
      <div class="mb-auto mt-auto text-center">
        <%= yield %>
      </div>

      <div class="row">
        <div class="col-md-12 text-center">
          <%= render partial: 'shared/footer', locals: { styles: 'application-footer' } %>
        </div>
      </div>
    </div>
    <%= render 'shared/alerts' %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= @page_title %> </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
  <meta name='keywords' content="<%= @seo_keywords %>"/>
  <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag 'favicons/favicon.ico' %>
  <% if Rails.env.production? %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-K8CS3TDTTP"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    </script>
  <% end %>
</head>

<body>
  <div class="container">
    <header class="blog-header py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <%= render 'shared/blog_header' %>
        <%= render 'shared/blog_navbar' %>
      </div>
    </header>

    <%= render 'shared/blog_nav_scroller' %>

    <main role="main" class="container">
      <div class="row">
        <%= yield %>
        <%= render 'shared/blog_sidebar' %>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= render partial: 'shared/footer', locals: { styles: 'blog-footer' } %>
          <%= source_helper('blog') %>
          <%= render 'shared/alerts' %>
        </div>
      </div>
    </main>
  </div>
</body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @page_title %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    <meta name='keywords' content="<%= @seo_keywords %>"/>
    <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <% if Rails.env.production? %>
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-K8CS3TDTTP"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
      </script>
    <% end %>
  </head>

  <body>
    <%= render 'shared/portfolio_navbar' %>
    
    <%= render 'shared/portfolio_masthead' %>

    <main role="main">
      <%= yield %>
      <%= render 'shared/portfolio_footer' %>
    </main>
      <%= render 'shared/alerts' %>
  </body>
</html>